service:
  name: serverless-image-optimizer-v8

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  memorySize: 2056
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: 
        - "arn:aws:s3:::ios-product-images-optimizer"
        - "arn:aws:s3:::ios-product-images-optimizer/*"

functions:
  s3_statements:
    handler: index.handler
    environment:
      BUCKET: ios-product-images-optimizer
    timeout: 60
    reservedConcurrency: 100
    layers:
      - arn:aws:lambda:ap-southeast-2:789885589778:layer:image-magick:1
    events:
      - s3:
          bucket: ios-product-images-optimizer
          event: s3:ObjectCreated:*
          rules:
            - prefix: originals/
